'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.42000
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ABB_RAPID_Prog_Helper.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Decoding Possible.
        '''</summary>
        Friend ReadOnly Property DecAvailable() As String
            Get
                Return ResourceManager.GetString("DecAvailable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Decoding completed.
        '''</summary>
        Friend ReadOnly Property DecFinished() As String
            Get
                Return ResourceManager.GetString("DecFinished", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Directory to decode.
        '''</summary>
        Friend ReadOnly Property DecFoldDesc() As String
            Get
                Return ResourceManager.GetString("DecFoldDesc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Saving the decoded directory.
        '''</summary>
        Friend ReadOnly Property DecFoldDescSave() As String
            Get
                Return ResourceManager.GetString("DecFoldDescSave", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Attention the directory:
        '''{0}
        '''  is not empty.
        '''Do you want to delete all of its content to continue?.
        '''</summary>
        Friend ReadOnly Property DecFoldMsg() As String
            Get
                Return ResourceManager.GetString("DecFoldMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Decoding in progress.
        '''</summary>
        Friend ReadOnly Property DecInProgress() As String
            Get
                Return ResourceManager.GetString("DecInProgress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Program Module (*.mod)|*.mod|System Module (*.sys)|*.sys|All|*.*.
        '''</summary>
        Friend ReadOnly Property DecOFDFilter() As String
            Get
                Return ResourceManager.GetString("DecOFDFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à File to decode.
        '''</summary>
        Friend ReadOnly Property DecOFDTitle() As String
            Get
                Return ResourceManager.GetString("DecOFDTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Program Module (*.mod)|*.mod|System Module (*.sys)|*.sys|All|*.*.
        '''</summary>
        Friend ReadOnly Property DecSFDFilter() As String
            Get
                Return ResourceManager.GetString("DecSFDFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Saving the Decoded File.
        '''</summary>
        Friend ReadOnly Property DecSFDTitle() As String
            Get
                Return ResourceManager.GetString("DecSFDTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Encoding Possible.
        '''</summary>
        Friend ReadOnly Property EncAvailable() As String
            Get
                Return ResourceManager.GetString("EncAvailable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Encoding completed.
        '''</summary>
        Friend ReadOnly Property EncFinished() As String
            Get
                Return ResourceManager.GetString("EncFinished", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Encoding in progress.
        '''</summary>
        Friend ReadOnly Property EncInProgress() As String
            Get
                Return ResourceManager.GetString("EncInProgress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Program Module (*.mod)|*.mod|System Module (*.sys)|*.sys|All|*.*.
        '''</summary>
        Friend ReadOnly Property EncOFDFilter() As String
            Get
                Return ResourceManager.GetString("EncOFDFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à File to Encode.
        '''</summary>
        Friend ReadOnly Property EncOFDTitle() As String
            Get
                Return ResourceManager.GetString("EncOFDTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Program Module (*.mod)|*.mod|System Module (*.sys)|*.sys|All|*.*.
        '''</summary>
        Friend ReadOnly Property EncSFDFilter() As String
            Get
                Return ResourceManager.GetString("EncSFDFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Saving the Encoded File.
        '''</summary>
        Friend ReadOnly Property EncSFDTitle() As String
            Get
                Return ResourceManager.GetString("EncSFDTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Please note the file: {0} already exists!
        '''Do you want to overwrite it?.
        '''</summary>
        Friend ReadOnly Property FileAlreadyExist() As String
            Get
                Return ResourceManager.GetString("FileAlreadyExist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Please note that the file: {0} does not appear to be encoded.
        '''Check this file before restarting the manipulation..
        '''</summary>
        Friend ReadOnly Property FileNotCoded() As String
            Get
                Return ResourceManager.GetString("FileNotCoded", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à File: {0} does not exist!.
        '''</summary>
        Friend ReadOnly Property NoFileExist() As String
            Get
                Return ResourceManager.GetString("NoFileExist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Error entering text:.
        '''</summary>
        Friend ReadOnly Property VerifTextError() As String
            Get
                Return ResourceManager.GetString("VerifTextError", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
